# MATCH
match_id = 'match_id'
match_date = 'match_date'
kick_off = 'kick_off'
home_team = 'home_team'
away_team = 'away_team'
home_team_id = 'home_team_id'
home_team_name = 'home_team_name'
away_team_id = 'away_team_id'
away_team_name = 'away_team_name'
home_score = 'home_score'
away_score = 'away_score'
stadium_name = 'stadium_name'
referee_name = 'referee_name'
match_status = 'match_status'
last_updated = 'last_updated'
data_version = 'data_version'

# COMPETITION
competition = 'competition'
competition_id = 'competition_id'
competition_name = 'competition_name'
country_name = 'country_name'
match_updated = 'match_updated'
match_available = 'match_available'

# SEASON
season = 'season'
season_id = 'season_id'
season_name = 'season_name'